services:
  frontend:
    build:
      context: .
      dockerfile: deploy/Dockerfile
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
        VITE_FILE_SERVICE_URL: ${VITE_FILE_SERVICE_URL}
        VITE_WS_URL: ${VITE_WS_URL}

    ports:
      - "3000:80"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - ms-net

    restart: unless-stopped

networks:
  ms-net:
    external: true

